title: Exploration
description: Simulations of autonomous robot navigation, using information-theoretic metrics.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
