new_http_archive(
    name = "gtest",
    url = "https://github.com/google/googletest/archive/release-1.7.0.zip",
    build_file = "gtest.BUILD",
    strip_prefix = "googletest-release-1.7.0",
)

new_http_archive(
    name = "glog",
    url = "https://github.com/google/glog/archive/v0.3.4.zip",
    build_file = "glog.BUILD",
    strip_prefix = "glog-0.3.4",
)

new_http_archive(
    name = "eigen",
    url = "http://bitbucket.org/eigen/eigen/get/3.3.0.zip",
    build_file = "eigen.BUILD",
    strip_prefix = "eigen-eigen-26667be4f70b",
)